### ISSUE TITLE
Initial Drive Code

### ISSUE THREAD

**Issue by schreiaj** [FRC125/NU14#1]
We need to be able to drive the robot with Tank style controls. 

This means we need control of all 6 motors in the drive base (Talons) 

For now you can safely assume we are using a pair of joysticks.

**Comment by ghost** [comment]
(In DTManualTankCmd.java)

``` java
dt.driveLR(oi.getDriveLeft(), oi.getDriveRight());
```

Should that be enough for now or is there more that we should do?

**Comment by schreiaj** [comment]
Closing due to commit a2d2e3057d00dffd04c9659b0b74b44082b2e988
