### ISSUE TITLE
Controls/Operator Interface

### ISSUE THREAD

**Issue by gracepetryk** [FRC125/NU14#11]
we still need controls to drive and operate the robot

**Comment by schreiaj** [comment]
Good point, talk to the chassis driver to see what they would prefer to drive with. If they don't have a preference pull out a gamepad and get it working. Consider driving around the old kitbot frame we have put together. 

But the big step is figuring out what actions we need the drivers to do. Could someone start a list in the wiki and we can start creating issues for them as they get more nailed down.

**Comment by schreiaj** [comment]
Since no action was taken on this.. There's a list of actions in the wiki https://github.com/FRC125/NU14/wiki/Operator-Actions  please review and add as we see fit.
